# Generated by Django 5.2.4 on 2025-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('cover_image', models.URLField(verbose_name='URL de la Portada')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
    ]